
trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- script:
- task: DownloadSecureFile@1
  inputs:
    secureFile: 'CC-KEY'
    workingDirectory: '$(System.DefaultWorkingDirectory)'

- task: CopyFiles@2
  displayName: 'Copy file'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    OverWrite: true 
    Contents: |
      **/playbook.yml
      **/cria_host.sh
    TargetFolder: '/tmp/clswap/'


- task: TerraformTaskV2@2
  inputs:
    workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/'
    provider: 'aws'
    command: 'init'
    backendServiceAWS: 'llteodoro-tis-automation-challenge'
    backendAWSBucketName: 'https://tis-automation-challenge.s3.amazonaws.com/tf-state/'
    backendAWSKey: 'https://tis-automation-challenge.s3.amazonaws.com/tf-state/terraform.tfstate'

- task: TerraformTaskV2@2
  inputs:
    workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/'
    environmentServiceNameAWS: 'llteodoro-tis-automation-challenge'
    provider: 'aws'
    command: 'plan'
    backendServiceAWS: 'llteodoro-tis-automation-challenge'
    backendAWSBucketName: 'https://tis-automation-challenge.s3.amazonaws.com/tf-state/'
    backendAWSKey: 'https://tis-automation-challenge.s3.amazonaws.com/tf-state/terraform.tfstate'

- task: TerraformTaskV2@2
  inputs:
    workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/'
    provider: 'aws'
    command: 'apply'
    commandOptions: '-auto-approve'
    environmentServiceNameAWS: 'llteodoro-tis-automation-challenge'
    backendServiceAWS: 'llteodoro-tis-automation-challenge'
    backendAWSBucketName: 'https://tis-automation-challenge.s3.amazonaws.com/tf-state/'
    backendAWSKey: 'https://tis-automation-challenge.s3.amazonaws.com/tf-state/terraform.tfstate'

- task: 
  displayName: Executing Container
  inputs:
    command: 'run'
    arguments: '--rm -v /tmp/clswap/:/tmp/clswap llteodoro/ansible:1.0 ansible-playbook -i /tmp/clswap/Swap_Clean/hosts_pipeline /tmp/clswap/Swap_Clean/playbook.yml --extra-vars "ansible_user=$(user) ansible_password=$(user_pwd)" -vvv'