
trigger:
- main

pool:
  vmImage: ubuntu-latest

parameters: 
  - name: workingDirectory 
    type: 
    string default: "$(Build.SourcesDirectory)/ansible
steps:

- script:


- task: TerraformTaskV3@3
  inputs:
    workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/'
    provider: 'aws'
    command: 'init'
    environmentServiceNameAWS: 'llteodoro-tis-automation-challenge'
    backendServiceAWS: 'llteodoro-tis-automation-challenge'
    backendAWSBucketName: 'tis-automation-challenge'
    backendAWSKey: 'tf-state/terraform.tfstate'

- task: TerraformTaskV3@3
  inputs:
    workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/'
    provider: 'aws'
    command: 'plan'
    environmentServiceNameAWS: 'llteodoro-tis-automation-challenge'
    backendServiceAWS: 'llteodoro-tis-automation-challenge'
    backendAWSBucketName: 'tis-automation-challenge'
    backendAWSKey: 'tf-state/terraform.tfstate'

- task: TerraformTaskV3@3
  inputs:
    workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/'
    provider: 'aws'
    command: 'apply'
    commandOptions: '-auto-approve'
    environmentServiceNameAWS: 'llteodoro-tis-automation-challenge'
    backendServiceAWS: 'llteodoro-tis-automation-challenge'
    backendAWSBucketName: 'tis-automation-challenge'
    backendAWSKey: 'tf-state/terraform.tfstate'
    
- task: DownloadSecureFile@1
  inputs:
    secureFile: 'challenge-key.pem'
    
#- task: CopyFiles@2
#  displayName: 'Copy file'
#  inputs:
#    SourceFolder: '$(Build.SourcesDirectory)'
#    OverWrite: true 
#    Contents: |
#      **/ansible/**
#    TargetFolder: '$(System.DefaultWorkingDirectory)/tmp/challenge-automation/'
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x' 
    addToPath: true 
    architecture: 'x64'

#- task: Docker@2
#  displayName: Executing Container
#  inputs:
#    command: 'run'
#    arguments: '--rm -v $(System.DefaultWorkingDirectory)/tmp/challenge-automation/:$(System.DefaultWorkingDirectory)/tmp/challenge-automation/ llteodoro/ansible:1.1 ansible-playbook -i $(System.DefaultWorkingDirectory)/tmp/challenge-automation/ansible/inventory.aws.ec2.yml $(System.DefaultWorkingDirectory)/tmp/challenge-automation/ansible/playbook-linux.yml -u ubuntu --private-key challenge-key.pem" -vvv'
- task: CmdLine@2
  displayName: Install Dependencies 
  inputs:
    workingDirectory: '${{ parameters.workingDirectory }}'
    script: |
      export AWS_ACCES_KEY_ID=$(AWS_ACCES_KEY_ID)
      export AWS_SECRET_ACCESS_KEY=$(AWS_ACCES_KEY_SECRET)
      sudo apt-get install -y python-wheel
      pipenv -m venv .venv && source .venv/bin/activate
      python3 -m pip install "ansible"
      python3 -m pip install "botocore"
      python3 -m pip install "boto3"
      ANSIBLE_HOST_KEY_CHECKING=False
      ansible-inventory -i inventory_aws_ec2.yml --graph
      ansible-playbook -i inventory.aws.ec2.yml playbook-linux.yml -u ubuntu --private-key challenge-key.pem

#- task: Ansible@0
#  inputs:
#    ansibleInterface: 'agentMachine'
#    playbookPathOnAgentMachine: '/tmp/challenge-automation/ansible/playbook-linux.yml'
#    inventoriesAgentMachine: 'file'
#    inventoryFileOnAgentMachine: '/tmp/challenge-automation/ansible/inventory_aws_ec2.yml'

#- task: CmdLine@2
#  displayName: Run Ansible Playbook Linux
#  inputs:
#   script: |
#     cd /tmp/tis-cc-automation/ansible
#     python3 -m venv .venv && source .venv/bin/activate
#     ansible-playbook -i inventory_aws_ec2.yml playbook-linux.yml -u ubuntu --private-key challenge-key.pem

#- task: CmdLine@3
#  displayName: Run Ansible Playbook Windows
#  inputs:
#    script: |
#    cd /tmp/tis-cc-automation
#    python3 -m venv venv
#    source venv/bin/activate
#    ansible-playbook -i inventory_aws_ec2.yml playbook-linux.yml -u ubuntu -private-key challenge-key.pem