
trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- script:

- task: DownloadSecureFile@1
  inputs:
    secureFile: 'challenge-key.pem'
    
- task: CopyFiles@2
  displayName: 'Copy file'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    OverWrite: true 
    Contents: |
      **/ansible/inventory_aws_ec2.yml
      **/ansible/playbook-linux.yml
      **/ansible/playbook-windows.yml
      **/ansible/index.html
    TargetFolder: '/tmp/tis-cc-automation/'


- task: TerraformTaskV2@2
  inputs:
    workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/'
    provider: 'aws'
    command: 'init'
    backendServiceAWS: 'llteodoro-tis-automation-challenge'
    backendAWSBucketName: 'https://tis-automation-challenge.s3.amazonaws.com/tf-state/'
    backendAWSKey: 'https://tis-automation-challenge.s3.amazonaws.com/tf-state/terraform.tfstate'

- task: TerraformTaskV2@2
  inputs:
    workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/'
    environmentServiceNameAWS: 'llteodoro-tis-automation-challenge'
    provider: 'aws'
    command: 'plan'
    backendServiceAWS: 'llteodoro-tis-automation-challenge'
    backendAWSBucketName: 'https://tis-automation-challenge.s3.amazonaws.com/tf-state/'
    backendAWSKey: 'https://tis-automation-challenge.s3.amazonaws.com/tf-state/terraform.tfstate'

- task: TerraformTaskV2@2
  inputs:
    workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/'
    provider: 'aws'
    command: 'apply'
    commandOptions: '-auto-approve'
    environmentServiceNameAWS: 'llteodoro-tis-automation-challenge'
    backendServiceAWS: 'llteodoro-tis-automation-challenge'
    backendAWSBucketName: 'https://tis-automation-challenge.s3.amazonaws.com/tf-state/'
    backendAWSKey: 'https://tis-automation-challenge.s3.amazonaws.com/tf-state/terraform.tfstate'

- task: 
  displayName: Executing Container
  inputs:
    command: 'run'
    arguments: '--rm -v /tmp/tis-cc-automation/:/tmp/tis-cc-automation/ llteodoro/ansible:1.0 ansible-playbook -i /tmp/tis-cc-automation/inventory_aws_ec2.yaml /tmp/tis-cc-automation/playbook-linux.yml --extra-vars "ansible_user=$(user-linux) --private-key=challenge-key.pem -vvv'