
trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: TerraformTaskV2@2
  inputs:
    workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/'
    provider: 'aws'
    command: 'init'
    backendServiceAWS: 'llteodoro-tis-automation-challenge'
    backendAWSBucketName: 'https://tis-automation-challenge.s3.amazonaws.com/tf-state/'
    backendAWSKey: 'https://tis-automation-challenge.s3.amazonaws.com/tf-state/terraform.tfstate'

- task: TerraformTaskV2@2
  inputs:
    workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/'
    environmentServiceNameAWS: 'development-cloud'
    provider: 'aws'
    command: 'plan'
    backendServiceAWS: 'llteodoro-tis-automation-challenge'
    backendAWSBucketName: 'https://tis-automation-challenge.s3.amazonaws.com/tf-state/'
    backendAWSKey: 'https://tis-automation-challenge.s3.amazonaws.com/tf-state/terraform.tfstate'

