- name: Create IP address
  hosts: localhost
  gather_facts: no

  vars:
    service_account_file: ansible-admin.json
    project: tis-cc-challenge
    auth_kind: serviceaccount
    scopes:
      - https://www.googleapis.com/auth/compute

  tasks:

   - name: Allocate an IP Address
     gcp_compute_address:
         state: present
         name: 'test-address1'
         region: 'us-west1'
         project: tis-cc-challenge
         auth_kind: serviceaccount
         service_account_file: ansible-admin.json
         scopes:
              - https://www.googleapis.com/auth/compute
