---
- hosts: tagGroupWebserver_Linux
  user: ubuntu
  vars:
    app_user: apache
    http_conf: apache.conf
    http_port: 80
    disable_default: true
    host_key_checking : False


  tasks:
  - name: Add the user apache with a specific uid and a primary group of 'admin'
    become: true
    ansible.builtin.user:
      name: apache
      comment: Apache User service
      uid: 1040
      group: admin
  
  - name: "Update Cache and Install Apache"
    become: true
    apt:
      name: apache2
      state: latest
      update_cache: yes

  - name: Copy Files 
    become: true 
    copy:
      src: ./index.html
      dest: /var/www/localhost/html
  
  - name: Create document root
    become: true
    file:
        path: "/var/www/localhost"
        state: directory
        owner: "{{ app_user }}"
        mode: '0755'
   
  - name: Set up Apache virtuahHost
    become: true
    template:
        src: "./apache.conf"
        dest: "/etc/apache2/sites-available/{{ http_conf }}"    
  
  - name: Enable new site
    become: true
    shell: /usr/sbin/a2ensite {{ http_conf }}
    notify: Reload Apache

  - name: Disable default Apache site
    become: true
    shell: /usr/sbin/a2dissite 000-default.conf
    when: disable_default
    notify: Reload Apache

  - name: "UFW - Allow HTTP on port {{ http_port }}"
    become: true
    ufw:
        rule: allow
        port: "{{ http_port }}"
        proto: tcp


  handlers:
    - name: Reload Apache
      become: true
      service:
        name: apache2
        state: reloaded

    - name: Restart Apache
      become: true
      service:
        name: apache2
        state: restarted  