---
- name: Install Apache from an MSI 

  hosts: tagGroupWebserver_Windows
 
  tasks:
    - name: Download the Apache installer
      win_get_url:
        url: 'http://mirror.cc.columbia.edu/pub/software/apache//httpd/binaries/win32/httpd-2.2.25-win32-x86-no_ssl.msi'
        dest: 'C:\Users\Administrator\Downloads\httpd-2.2.25-win32-x86-no_ssl.msi'

    - name: Install MSI

      win_package:

        path: C:\ansible_examples\httpd-2.2.25-win32-x86-no_ssl.msi

        arguments:

          - /install

          - /passive
          
          - /norestart
    
    - name: Copy File
      win_copy:
        src: ./index.html
        dest: C:\Apache24\htdocs\
        remote_src: yes